services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_WORKDIR=${DOCKER_WORKDIR}
    env_file:
      - .app.env
    environment:
      - CHROME_EXECUTABLE_PATH=/root/.cache/ms-playwright/chromium-1112/chrome-linux/chrome
    volumes:
      - type: bind
        source: ./downloads
        target: ${DOCKER_WORKDIR}/downloads
      - type: bind
        source: ./urls
        target: ${DOCKER_WORKDIR}/urls