name: copy-paste

services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_WORKDIR=${DOCKER_WORKDIR}
    hostname: scraper
    volumes:
      - type: bind
        source: ./dist
        target: ${DOCKER_WORKDIR}/dist
